### ISSUE TITLE
Upgrade downshift to ^8

### ISSUE THREAD

**Issue by mglaman** [simplytestme/website#220]
https://github.com/simplytestme/website/pull/193 shows that we're not compatible with Downshift ^8

```
TypeError: h is not a function
    at Ve (ProjectAutocomplete.js:78:13)
    at oo (react-dom.production.min.js:157:137)
    at Ki (react-dom.production.min.js:267:460)
    at ju (react-dom.production.min.js:250:347)
    at Ou (react-dom.production.min.js:250:278)
    at _u (react-dom.production.min.js:250:138)
    at bu (react-dom.production.min.js:243:163)
    at hu (react-dom.production.min.js:237:175)
    at es (react-dom.production.min.js:285:27)
    at react-dom.production.min.js:289:301
```

**Comment by mglaman** [comment]
Moved to https://www.drupal.org/project/simplytest/issues/3423288
